### ISSUE TITLE
Tombol Refresh tidak bekerja

### ISSUE THREAD

**Issue by rachyharkov** [Zzzul/transaction-form#1]
Harusnya work kan ya? reset tampilan transaksi seperti semula

![image](https://user-images.githubusercontent.com/44340813/101276662-10906580-37e1-11eb-8629-5a6f1640f29d.png)

**Comment by rachyharkov** [comment]
#
#2 Pull Request - Menyempurnakan bagian yang tidak fungsi  
Ini sudah saya sempurnakan, semoga bermanfaat dan tidak mengacaukan ya ^_^
> Harusnya work kan ya? reset tampilan transaksi seperti semula
> 
> ![image](https://user-images.githubusercontent.com/44340813/101276662-10906580-37e1-11eb-8629-5a6f1640f29d.png)

**Comment by Zzzul** [comment]
Done mat

**Comment by rachyharkov** [comment]
aokwoakokaw, tau darimana u manggil gua mat mi, budet

thx dah dicommit, mudah2an karya u manfaat buat orang laen, semangat mgodonf

**Comment by Zzzul** [comment]
yoii thx juga udah kontribusi.
salam javirascript, jgn lupa shuwodon PC
